AllCops:
  NewCops: enable
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'

Metrics/MethodLength:
  CountAsOne: ['hash']

Naming/VariableNumber:
  # Jira has wacko field names, which are reflected
  # in the hashes which get turned into json.
  CheckSymbols: false
