#!/usr/bin/env ruby

# frozen-string-literal: true

require 'pp'
require 'ap'
require 'pry'
require 'rest-client'
require 'json'
require 'aws-sdk-s3'
require 'csv'

require_relative 'lib/account_manager'
require_relative 'lib/api_helper'

api_keys = AccountManager.new.api_keys
USERNAME = api_keys[:jira_id]
PASSWORD = api_keys[:jira_key]

# Helper class for keep in the json generation under control.
class Issue
  def initialize(project_key: 'SCRUM', issuetype_name: 'Task')
    @project_key = project_key
    @issuetype_name = issuetype_name
    @gem = 'rails'
    @version = '6.0.3.4'
  end

  def summary
    raise NotImplementedError # "update  #{@gem} gem to version #{@version}"
  end

  def description
    'updating a ruby gem'
  end

  def issuetype
    { "name": @issuetype_name }
  end

  def labels
    raise NotImplementedError # ['maintenance']
  end

  def acceptance_criteria
    'ensure all specs and features pass'
    # {
    #   "version": 1,
    #   "type": 'doc',
    #   "content": [
    #     {
    #       "type": 'paragraph',
    #       "content": [
    #         { "type": 'text', "text": 'Here is the autogenerated acceptance criteria.' }
    #       ]
    #     }
    #   ]
    # }
  end

  def project
    { "key": @project_key }
  end

  def time_estimate
    { "originalEstimate": '15m' }
  end

  def to_h
    {
      fields: {
        project: project,
        summary: summary,
        description: description,
        issuetype: issuetype,
        labels: labels,
        timetracking: time_estimate,
        customfield_10029: acceptance_criteria
      }
    }
  end
end

# Subclass to reduce cognitive load
class GemIssue < Issue
  def summary
    "update  #{@gem} gem to version #{@version}"
  end

  def labels
    ['maintenance']
  end
end

# params = JSON.parse(File.read('./test.json'))

# puts 'EXITING NOW so as not to mess up the board, check parameters before proceeding.'
# exit

_ticket = OpenStruct.new(
  projecct: 'TASKLETS',
  labels: ['maintenance'],
  gem: 'rails',
  version: '6.0.3.4'
)

# project = 'TASKLETS'
project = 'SCRUM'

params = GemIssue.new(project_key: project).to_h

api_url = 'https://doolin.atlassian.net/rest/api/2/issue/'
api_helper = ApiHelper.new(api_url)
api_helper.post(params)
