name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.1'
          bundler-cache: true

      - name: Bundler audit
        run: |
          bundle exec bundle audit update
          bundle exec bundle audit check

      - name: RSpec
        run: bundle exec rspec

      - name: RuboCop
        run: bundle exec rubocop
