# frozen_string_literal: true

# Helper class for keep in the json generation under control.
class Issue
  def initialize(ticket)
    @project_key = ticket.project_key
    @issuetype_name = ticket.issuetype_name
    @gem = ticket.gem
    @version = ticket.version
  end

  def summary
    raise NotImplementedError # "update  #{@gem} gem to version #{@version}"
  end

  def description
    raise NotImplementedError
  end

  def issuetype
    { name: @issuetype_name }
  end

  def labels
    raise NotImplementedError # ['maintenance']
  end

  def acceptance_criteria
    'ensure all specs and features pass'
    # {
    #   "version": 1,
    #   "type": 'doc',
    #   "content": [
    #     {
    #       "type": 'paragraph',
    #       "content": [
    #         { "type": 'text', "text": 'Here is the autogenerated acceptance criteria.' }
    #       ]
    #     }
    #   ]
    # }
  end

  def project
    { key: @project_key }
  end

  def time_estimate
    { originalEstimate: '15m' }
  end

  def to_h
    {
      fields: {
        project:,
        summary:,
        description:,
        issuetype:,
        labels:,
        timetracking: time_estimate,
        customfield_10029: acceptance_criteria
      }
    }
  end
end
